// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.startrack


case class ChoiceTypeType(consignmentId: Seq[String] = Nil,
  senderReferenceNumber: Seq[String] = Nil)


case class ConsignmentStatusesType(status: Option[String] = None,
  total: Option[String] = None)


case class ConsignmentTypesType(typeValue: Option[String] = None,
  total: Option[String] = None)


case class DespatchChoiceType(serviceType: Seq[org.birchavenue.startrack.ServiceTypeEnum] = Nil,
  despatchLocationCode: String,
  despatchDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  status: Option[String] = None)


case class GetConsignmentDetailChoiceType(consignmentId: Seq[String] = Nil,
  despatch: Option[org.birchavenue.startrack.DespatchChoiceType] = None,
  includeEvents: Option[Boolean] = None)


case class MatchingConsignmentsType(payerAccountNumber: Option[String] = None,
  despatchLocationCode: Seq[String] = Nil,
  total: Option[String] = None)


case class PersonSearchType(name: Option[String] = None,
  suburb: Option[String] = None,
  state: Option[String] = None,
  postCode: Option[String] = None)


case class SearchConsignmentRequestType(consignmentType: Seq[String] = Nil,
  despatchFromDate: javax.xml.datatype.XMLGregorianCalendar,
  despatchToDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  etaFromDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  etaToDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  deliveryFromDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  deliveryToDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class SearchConsignmentType(id: Option[String] = None,
  source: Option[String] = None,
  status: Option[String] = None,
  typeValue: Option[String] = None,
  serviceCode: Option[String] = None,
  despatchDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  payerAccountNumber: Option[BigInt] = None,
  etaDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  payerType: Option[String] = None,
  despatchLocationCode: Option[String] = None,
  receiver: Option[org.birchavenue.startrack.ReceiverTypeType] = None,
  references: Option[org.birchavenue.startrack.ReferenceTypeType] = None,
  lastStatusDatetime: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  podSignatoryName: Option[String] = None,
  dangerousGoods: Option[Boolean] = None,
  podSignature: Option[String] = None)


case class Tp_choiceType(consignmentId: Seq[String] = Nil,
  senderReferenceNumber: Seq[String] = Nil)


case class Tp_consignmentType(serviceCode: Option[String] = None,
  secondaryQcCode: Seq[String] = Nil,
  receiver: Option[org.birchavenue.startrack.Tp_partnerType] = None,
  sender: Option[org.birchavenue.startrack.Tp_partnerType] = None,
  specialInstructions: Seq[String] = Nil,
  despatchLocationCode: Option[String] = None,
  references: Seq[org.birchavenue.startrack.ReferenceTypeType] = Nil,
  statusHistory: Seq[org.birchavenue.startrack.StatusHistoryType] = Nil,
  trackingEvents: Seq[org.birchavenue.startrack.ConsignmentTrackingEventType] = Nil,
  lineItems: Seq[org.birchavenue.startrack.LineItemTypeType] = Nil,
  dangerousGoods: Option[org.birchavenue.startrack.DGType] = None,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val billedInd = attributes.get("@billedInd") map { _.as[Boolean] }
  lazy val bookInNotAfter = attributes.get("@bookInNotAfter") map { _.as[javax.xml.datatype.XMLGregorianCalendar] }
  lazy val bookInNotBefore = attributes.get("@bookInNotBefore") map { _.as[javax.xml.datatype.XMLGregorianCalendar] }
  lazy val carrierCode = attributes.get("@carrierCode") map { _.as[String] }
  lazy val consolidate = attributes.get("@consolidate") map { _.as[Boolean] }
  lazy val consolidateSendersReference = attributes.get("@consolidateSendersReference") map { _.as[Boolean] }
  lazy val creationDateTime = attributes.get("@creationDateTime") map { _.as[javax.xml.datatype.XMLGregorianCalendar] }
  lazy val deliveryDepot = attributes.get("@deliveryDepot") map { _.as[String] }
  lazy val despatchDate = attributes.get("@despatchDate") map { _.as[javax.xml.datatype.XMLGregorianCalendar] }
  lazy val despatchDepot = attributes.get("@despatchDepot") map { _.as[String] }
  lazy val despatchNotification = attributes.get("@despatchNotification") map { _.as[Boolean] }
  lazy val despatchSummaryId = attributes.get("@despatchSummaryId") map { _.as[String] }
  lazy val driverCube = attributes.get("@driverCube") map { _.as[BigDecimal] }
  lazy val etaDate = attributes.get("@etaDate") map { _.as[javax.xml.datatype.XMLGregorianCalendar] }
  lazy val id = attributes.get("@id") map { _.as[String] }
  lazy val labelText = attributes.get("@labelText") map { _.as[String] }
  lazy val labelText_2 = attributes.get("@labelText_2") map { _.as[String] }
  lazy val labelText_3 = attributes.get("@labelText_3") map { _.as[String] }
  lazy val lastStatusDateTime = attributes.get("@lastStatusDateTime") map { _.as[javax.xml.datatype.XMLGregorianCalendar] }
  lazy val lock_seq = attributes.get("@lock_seq") map { _.as[String] }
  lazy val payerType = attributes.get("@payerType") map { _.as[String] }
  lazy val podSignatoryName = attributes.get("@podSignatoryName") map { _.as[String] }
  lazy val podSignature = attributes.get("@podSignature") map { _.as[String] }
  lazy val publishedQcCode = attributes.get("@publishedQcCode") map { _.as[String] }
  lazy val quotationNumber = attributes.get("@quotationNumber") map { _.as[String] }
  lazy val requestService = attributes.get("@requestService") map { _.as[Boolean] }
  lazy val source = attributes.get("@source") map { _.as[String] }
  lazy val status = attributes.get("@status") map { _.as[String] }
  lazy val totalQuantity = attributes.get("@totalQuantity") map { _.as[BigInt] }
  lazy val totalVolume = attributes.get("@totalVolume") map { _.as[Double] }
  lazy val totalWeight = attributes.get("@totalWeight") map { _.as[Double] }
  lazy val typeValue = attributes.get("@type") map { _.as[String] }
  lazy val unitType = attributes.get("@unitType") map { _.as[String] }
  lazy val userName = attributes.get("@userName") map { _.as[String] }
}



case class Tp_partnerType(addressLine1: Option[String] = None,
  addressLine2: Option[String] = None,
  addressLine3: Option[String] = None,
  country: Option[String] = None,
  id: Option[String] = None,
  name: Option[String] = None,
  postCode: Option[String] = None,
  shortName: Option[String] = None,
  state: Option[String] = None,
  suburb: Option[String] = None)


case class Tp_searchConsignmentType(id: Option[String] = None,
  source: Option[String] = None,
  status: Option[String] = None,
  typeValue: Option[String] = None,
  serviceCode: Option[String] = None,
  despatchDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  etaDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  payerType: Option[String] = None,
  despatchLocationCode: Option[String] = None,
  receiver: Option[org.birchavenue.startrack.Tp_partnerType] = None,
  lastStatusDatetime: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  podSignatoryName: Option[String] = None,
  dangerousGoods: Option[Boolean] = None)


case class Fault3(fs_code: Option[String] = None,
  fs_category: Option[org.birchavenue.startrack.FaultCategoryType] = None,
  fs_severity: Option[org.birchavenue.startrack.FaultSeverityType] = None,
  fs_timestamp: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  fs_message: Option[String] = None,
  fs_logicalComponentId: Option[String] = None,
  fs_physicalComponentId: Option[String] = None,
  fs_system: Option[String] = None,
  fs_correlationId: Option[String] = None,
  fs_faultPayload: Option[String] = None)


case class GetConsignmentDetailRequest(header: org.birchavenue.startrack.TransactionHeaderType,
  consignmentId: Seq[String] = Nil)


case class GetConsignmentDetailResponse(consignment: org.birchavenue.startrack.ConsignmentType*)


case class SearchConsignmentsRequest(header: org.birchavenue.startrack.TransactionHeaderType,
  choice: Option[org.birchavenue.startrack.ChoiceTypeType] = None,
  consignmentType: Option[org.birchavenue.startrack.SearchConsignmentRequestType] = None,
  serviceCode: Seq[String] = Nil,
  consignmentStatus: Seq[String] = Nil,
  receiver: Option[org.birchavenue.startrack.PersonSearchType] = None,
  sender: Option[org.birchavenue.startrack.PersonSearchType] = None,
  despatchLocationCode: Seq[String] = Nil,
  dangerousGoodsOnly: Option[Boolean] = None,
  pagination: org.birchavenue.startrack.PaginationType)


case class SearchConsignmentsResponse(consignmentSummary: Seq[org.birchavenue.startrack.SearchConsignmentType] = Nil,
  pagination: org.birchavenue.startrack.PaginationType)


case class Tp_getConsignmentDetailRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  consignmentId: Seq[String] = Nil)


case class Tp_getConsignmentDetailResponse(consignment: org.birchavenue.startrack.Tp_consignmentType*)


case class Tp_getFreightItemDetailRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  freightItemId: Seq[String] = Nil)


case class Tp_getFreightItemDetailResponse(consignment: org.birchavenue.startrack.Tp_consignmentType*)


case class Tp_searchConsignmentsRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  choice: org.birchavenue.startrack.Tp_choiceType,
  pagination: org.birchavenue.startrack.PaginationType)


case class Tp_searchConsignmentsResponse(consignmentSummary: Seq[org.birchavenue.startrack.Tp_searchConsignmentType] = Nil,
  pagination: org.birchavenue.startrack.PaginationType)

