// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.startrack


case class DepotTypeType2(depotCode: String,
  depotName: Option[String] = None,
  depotAbbreviation: Option[String] = None,
  adminDepotCode: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None) extends DepotTypable


case class GetDepotCutOffTimeComplex(depotCode: Option[String] = None,
  depotName: Option[String] = None,
  airBookingCutOff: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  roadBookingCutOff: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  airPickupCutOff: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  roadPickupCutOff: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  adminDepotCode: Option[String] = None,
  lock_seq: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None) extends DepotCutOffTimeComplexable


case class LocationTypeType(locationId: Option[String] = None,
  locationDetails: Option[org.birchavenue.startrack.LocationDetailsType] = None,
  nearestDepotCode: Option[String] = None,
  primaryAirDepotCode: Option[String] = None,
  secondaryAirDepotCode: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  visualSuburb: Option[String] = None) extends LocationTypable


case class QCCodeTypeType(qcCode: String,
  qcDescription: Option[String] = None,
  isSelectable: Option[Boolean] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None) extends QCCodeTypable


case class ScanModeTypeType(scanMode: org.birchavenue.startrack.ScanModeHeaderType,
  scanDescription: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None) extends ScanModeTypable


case class ServiceCodeComplexType(serviceCode: Option[String] = None,
  serviceDescription: Option[String] = None,
  serviceClass: Option[String] = None,
  serviceType: Option[String] = None,
  serviceRank: Option[BigInt] = None,
  publiclyViewable: Option[Boolean] = None,
  isDefault: Option[Boolean] = None,
  sortOrder: Option[BigInt] = None,
  transportType: Option[String] = None,
  tLabelText: Option[String] = None,
  fastServiceCode: Option[String] = None,
  newProduct: Option[Boolean] = None,
  applicability: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  lock_seq: Option[String] = None) extends ServiceCodeComplexable


case class SimpleLocationType(lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  nearestDepotCode: Option[String] = None,
  postCode: Option[String] = None,
  state: Option[String] = None,
  suburb: Option[String] = None,
  visualSuburb: Option[String] = None)


case class TransitStateTypeType(transitStateHeader: org.birchavenue.startrack.TransitStateHeaderType,
  transitStateDescription: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None) extends TransitStateTypable


case class GetDepotsRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  depotCode: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class GetDepotsResponse(depot: org.birchavenue.startrack.GetDepotCutOffTimeComplex*)


case class GetLocationsRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  locationDetails: org.birchavenue.startrack.LocationDetailsType,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class GetLocationsResponse(location: org.birchavenue.startrack.SimpleLocationType*)


case class GetNearestDepotRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  locationDetails: org.birchavenue.startrack.LocationDetailsType,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class GetNearestDepotResponse(depot: Option[org.birchavenue.startrack.DepotTypeType2] = None,
  locations: Seq[org.birchavenue.startrack.LocationTypeType] = Nil)


case class GetQCCodesRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  code: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class GetQCCodesResponse(qcCodes: org.birchavenue.startrack.QCCodeTypeType*)


case class GetServiceCodesRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  code: Option[String] = None,
  lastUpdated: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class GetServiceCodesResponse(codes: org.birchavenue.startrack.ServiceCodeComplexType*)


case class ValidateAddressRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  address: Option[org.birchavenue.startrack.AddressComplex] = None)


case class ValidateAddressResponse(exactMatchFound: Option[Boolean] = None,
  matchedAddress: Seq[org.birchavenue.startrack.MatchedAddressComplex] = Nil)

