// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.startrack


case class CreatePickupBookingRequest(header: org.birchavenue.startrack.TransactionHeaderType,
  pickupBooking: org.birchavenue.startrack.PickupBookingTypeType)


case class CreatePickupBookingResponse(pickupBookingId: org.birchavenue.startrack.PickupBookingIdType)


case class GetPickupCutoffTimesRequest(header: org.birchavenue.startrack.TransactionHeaderType,
  pickupCutoffParameters: org.birchavenue.startrack.PickupCutoffTime)


case class GetPickupCutoffTimesResponse(pickupCutoffDetails: org.birchavenue.startrack.LocationCutoffTimeComplex)


case class Tp_createPickupBookingRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  pickupBooking: org.birchavenue.startrack.PickupBookingTypeType)


case class Tp_createPickupBookingResponse(pickupBookingId: org.birchavenue.startrack.PickupBookingIdType)


case class Tp_getPickupCutoffTimesRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  pickupCutoffParameters: org.birchavenue.startrack.PickupCutoffTime)


case class Tp_getPickupCutoffTimesResponse(pickupCutoffDetails: org.birchavenue.startrack.LocationCutoffTimeComplex)

