// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.startrack


case class Fault(fs_code: Option[String] = None,
  fs_category: Option[org.birchavenue.startrack.FaultCategoryType] = None,
  fs_severity: Option[org.birchavenue.startrack.FaultSeverityType] = None,
  fs_timestamp: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  fs_message: Option[String] = None,
  fs_logicalComponentId: Option[String] = None,
  fs_physicalComponentId: Option[String] = None,
  fs_system: Option[String] = None,
  fs_correlationId: Option[String] = None,
  fs_faultPayload: Option[String] = None)

