// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.startrack


case class BookedPickupType(bookingId: String,
  createdDateTime: javax.xml.datatype.XMLGregorianCalendar,
  pickupDate: javax.xml.datatype.XMLGregorianCalendar)


case class CustomerAuthorisation(authorisationType: String,
  mustValidate: Boolean,
  isRequired: Boolean,
  allowedValue: Seq[String] = Nil)


case class PickupAccountType(accountNumber: BigInt,
  businessUnit: String,
  accountName: Seq[String] = Nil,
  status: String,
  pinRequired: Boolean,
  costCentreRequired: Boolean,
  employeeIDRequired: Boolean,
  purchaseOrderRequired: Boolean,
  customerReferenceRequired: Boolean,
  stopTrade: Boolean,
  customerAuthorisation: Seq[org.birchavenue.startrack.CustomerAuthorisation] = Nil)


case class PickupBookingTypeType(serviceCode: String,
  payerAccountNo: String,
  bookingSource: String,
  consignmentId: Option[String] = None,
  isPrePaid: Option[Boolean] = None,
  pickupDetails: org.birchavenue.startrack.PickupLocationDetailsType,
  deliveryDetails: Option[org.birchavenue.startrack.PickupLocationDetailsType] = None,
  specialInstructions: Seq[String] = Nil,
  pickupDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  timeReady: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  timeClosing: javax.xml.datatype.XMLGregorianCalendar,
  connoteRequired: Option[Boolean] = None,
  isPrivateAddress: Option[Boolean] = None,
  branchPrintLabels: Option[Boolean] = None,
  costCentre: Option[String] = None,
  employeeID: Option[String] = None,
  purchaseOrder: Option[String] = None,
  pickupFreightItems: Seq[org.birchavenue.startrack.PickupFreightItemGroupTypeType] = Nil,
  heaviestItemWeight: Option[BigDecimal] = None)


case class PickupCutoffTime(payerAccountNo: Option[String] = None,
  serviceCode: String,
  pickupDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  pickupLocation: org.birchavenue.startrack.AddressComplex)


case class PickupFreightItemGroupTypeType(quantity: Option[BigInt] = None,
  weight: Option[BigDecimal] = None,
  height: Option[BigInt] = None,
  width: Option[BigInt] = None,
  length: Option[BigInt] = None,
  unitType: Option[String] = None)


case class PickupLocationComplexType(index: Option[String] = None,
  accountNumber: BigInt,
  businessUnit: String,
  pickupCompanyName: Option[String] = None,
  pickupContact: Option[String] = None,
  pickupAddress: Option[org.birchavenue.startrack.AddressComplex] = None,
  pickupPhoneNumber: Option[String] = None,
  pickupEmailAddress: Option[String] = None,
  pickupPoint: Option[String] = None,
  closingTime: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  airCutoffTime: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  roadCutoffTime: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  nearestDepotCode: Option[String] = None,
  auspostLodgement: Option[Boolean] = None,
  regularPickup: Option[Boolean] = None,
  pickupIdentificationRequired: Option[String] = None,
  locationTimezone: Option[String] = None,
  currentTimeAtLocation: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  timePassed: Option[Boolean] = None,
  nextBusinessDay: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class PickupLocationDetailsType(companyName: Option[String] = None,
  contactName: Option[String] = None,
  contactPhone: Option[String] = None,
  contactMobilePhone: Option[String] = None,
  contactEmailAddress: Option[String] = None,
  contactPoint: Option[String] = None,
  locationDetails: org.birchavenue.startrack.AddressComplex)

