// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.startrack


trait DepotTypable {
  val depotCode: String
  val depotName: Option[String]
  val depotAbbreviation: Option[String]
  val adminDepotCode: Option[String]
}


case class DepotTypeType(depotCode: String,
  depotName: Option[String] = None,
  depotAbbreviation: Option[String] = None,
  adminDepotCode: Option[String] = None) extends DepotTypable


case class FreightItemIncidentType(freightItemIncidentCode: String,
  freightItemIncidentDescription: Option[String] = None)


trait LocationTypable {
  val locationId: Option[String]
  val locationDetails: Option[org.birchavenue.startrack.LocationDetailsType]
  val nearestDepotCode: Option[String]
  val primaryAirDepotCode: Option[String]
  val secondaryAirDepotCode: Option[String]
}


case class LocationType(locationId: Option[String] = None,
  locationDetails: Option[org.birchavenue.startrack.LocationDetailsType] = None,
  nearestDepotCode: Option[String] = None,
  primaryAirDepotCode: Option[String] = None,
  secondaryAirDepotCode: Option[String] = None) extends LocationTypable


trait QCCodeTypable {
  val qcCode: String
  val qcDescription: Option[String]
  val isSelectable: Option[Boolean]
}


case class QCCodeType(qcCode: String,
  qcDescription: Option[String] = None,
  isSelectable: Option[Boolean] = None) extends QCCodeTypable


trait ScanModeTypable {
  val scanMode: org.birchavenue.startrack.ScanModeHeaderType
  val scanDescription: Option[String]
}


case class ScanModeType(scanMode: org.birchavenue.startrack.ScanModeHeaderType,
  scanDescription: Option[String] = None) extends ScanModeTypable


trait TransitStateTypable {
  val transitStateHeader: org.birchavenue.startrack.TransitStateHeaderType
  val transitStateDescription: Option[String]
}


case class TransitStateType(transitStateHeader: org.birchavenue.startrack.TransitStateHeaderType,
  transitStateDescription: Option[String] = None) extends TransitStateTypable


case class UnitTypeType(unitType: String,
  unitDescription: Option[String] = None,
  unitRank: Option[BigInt] = None,
  publiclyViewable: Option[Boolean] = None,
  isDefault: Option[Boolean] = None,
  sortOrder: Option[BigInt] = None,
  isBulk: Option[Boolean] = None)

