// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.birchavenue.startrack


case class ChoiceType(despatchDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  arrivalDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class CalculateCostAndEstimatedTimeRequest(header: org.birchavenue.startrack.TransactionHeaderType,
  senderLocation: org.birchavenue.startrack.ExtLocationDetailsType,
  receiverLocation: org.birchavenue.startrack.ExtLocationDetailsType,
  serviceCode: String,
  noOfItems: BigInt,
  weight: BigDecimal,
  volume: BigDecimal,
  includeTransitWarranty: Option[Boolean] = None,
  transitWarrantyValue: Option[BigDecimal] = None,
  includeRiskWarranty: Option[Boolean] = None,
  riskWarrantyValue: Option[BigDecimal] = None,
  includeFuelSurcharge: Option[Boolean] = None,
  includeSecuritySurcharge: Option[Boolean] = None,
  choice: org.birchavenue.startrack.ChoiceType)


case class CalculateCostAndEstimatedTimeResponse(cost: Option[BigDecimal] = None,
  gstCharge: Option[BigDecimal] = None,
  fuelSurcharge: Option[BigDecimal] = None,
  securitySurcharge: Option[BigDecimal] = None,
  transitWarrantyCharge: Option[BigDecimal] = None,
  transitWarrantyValue: Option[BigDecimal] = None,
  riskWarrantyCharge: Option[BigDecimal] = None,
  riskWarrantyValue: Option[BigDecimal] = None,
  eta: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  etd: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class CalculateCostRequest(header: org.birchavenue.startrack.TransactionHeaderType,
  senderLocation: org.birchavenue.startrack.ExtLocationDetailsType,
  receiverLocation: org.birchavenue.startrack.ExtLocationDetailsType,
  serviceCode: String,
  noOfItems: BigInt,
  weight: BigDecimal,
  volume: BigDecimal,
  includeTransitWarranty: Option[Boolean] = None,
  transitWarrantyValue: Option[BigDecimal] = None,
  includeRiskWarranty: Option[Boolean] = None,
  riskWarrantyValue: Option[BigDecimal] = None,
  includeFuelSurcharge: Option[Boolean] = None,
  includeSecuritySurcharge: Option[Boolean] = None)


case class CalculateCostResponse(cost: Option[BigDecimal] = None,
  gstCharge: Option[BigDecimal] = None,
  fuelSurcharge: Option[BigDecimal] = None,
  securitySurcharge: Option[BigDecimal] = None,
  transitWarrantyCharge: Option[BigDecimal] = None,
  transitWarrantyValue: Option[BigDecimal] = None,
  riskWarrantyCharge: Option[BigDecimal] = None,
  riskWarrantyValue: Option[BigDecimal] = None)


case class CalculateEstimatedTimeRequest(header: org.birchavenue.startrack.TransactionHeaderType,
  senderLocation: org.birchavenue.startrack.ExtLocationDetailsType,
  receiverLocation: org.birchavenue.startrack.ExtLocationDetailsType,
  serviceCode: String,
  choice: org.birchavenue.startrack.ChoiceType,
  validateAddress: Option[Boolean] = None)


case class CalculateEstimatedTimeResponse(eta: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  etd: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class Tp_calculateEstimatedTimeRequest(header: org.birchavenue.startrack.Tp_TransactionHeaderType,
  senderLocation: org.birchavenue.startrack.ExtLocationDetailsType,
  receiverLocation: org.birchavenue.startrack.ExtLocationDetailsType,
  serviceCode: String,
  choice: org.birchavenue.startrack.ChoiceType,
  validateAddress: Option[Boolean] = None)

